[general]
individuals_per_method_and_depth = 10
generations = 1000

[generation]
p_grow_leaf = 0.1
min_gen_depth = 2
max_gen_depth = 6

[evaluation]
score_error = -10000.0
depth_softener = 6.0
max_program_runtime_ms = 10 # will error if running for longer
max_depth = 12 # will error if tree is deeper

[mutation]
mutation_chance = 0.05
mutation_single_chance = 0.1

[crossover]
crossover_size_proportion = 0.75

[selection]
    [selection.fitness]
    selection_pressure = 1.0

    [selection.tournament]
    tournament_size = 4
    tournament_p = 1.0